<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
    <Platforms>AnyCPU;ARM64</Platforms>
    <OutputType>Exe</OutputType>
    <StartupObject>Inventory.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Core" Version="1.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="System.Collections" Version="4.3.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataLayer\DataLayer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Views\Ordering\Payment.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Views\Ordering\Payment.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Views\InventoryControl\AddElectronic.cshtml" />
    <None Include="Views\Ordering\Payment.cshtml" />
  </ItemGroup>

</Project>
